BookTest/Models/Author.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace BookTest.Models
{
    public class Author
    {
        [JsonProperty(PropertyName= "id")]
        public int Id { get; set; }
        /// <summary>
        /// 名
        /// </summary>
        [Required]
        [Display(Name = "名")]

        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Required]
        [Display(Name = "姓")]
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

        [JsonProperty(PropertyName = "biography")]
        public string Biography { get; set; }

        [JsonProperty(PropertyName = "books")]
        public ICollection<Book> Books { get; set; }  
    }
}

BookTest/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Web;
using System.Web.ModelBinding;
using System.Web.Mvc;
using BookTest.DAL;
using BookTest.Models;

namespace BookTest.Controllers
{
    public class AuthorsController : Controller
    {
        private BookContext db = new BookContext();

        // GET: Authors
        public ActionResult Index([Form] QueryOptions queryOptions)
        {
            var authors =
                db.Authors.OrderBy(queryOptions.Sort)
                    .Skip((queryOptions.Page - 1)*queryOptions.PageSize)
                    .Take(queryOptions.PageSize);
            queryOptions.TotalPage = (int)Math.Ceiling((double)db.Authors.Count()/queryOptions.PageSize);
            ViewBag.QueryOptions = queryOptions;
            return View(authors.ToList());
        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        // GET: Authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookTest/Views/Authors/Create.cshtml
@model BookTest.Models.Author

@{
    ViewBag.Title = "Create";
}
<div data-bind="visible:!saveCompleted()">
    <h2>Create</h2>
    @using (Html.BeginForm("Create", "Authors", FormMethod.Post, new { data_bind = "submit:validateAndSave" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Author</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="col-md-10">
                    <p> firstName:<span data-bind="text:author.firstName"></span></p>
                    <p> lastName:<span data-bind="text:author.lastName"></span></p>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       data_bind = "value:author.firstName"
                   }
               })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>
 
            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       data_bind = "value:author.lastName"
                   }
               })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Biography, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Biography, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       data_bind = "value:author.biography"
                   }
               })
                    @Html.ValidationMessageFor(model => model.Biography, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" data-bind="visible:!sending()">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
                <div class="progress" data-bind="visible:sending()">
                    <div class="progress-bar progress-bar-info progress-bar-striped active"
                         role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"
                         style="width: 100%"><span class="sr-only"></span></div>
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/ViewModels/AuthorFormViewModel.js")
    <script>
        var viewModel = new AuthorFormViewModel();
        ko.applyBindings(viewModel);
    </script>
}

BookTest/Views/Authors/Delete.cshtml
@model BookTest.Models.Author

@{
    ViewBag.Title = "Delete";
    Layout = null;
}
<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title">Author Delete Confirmation</h4>
            </div>
            <div class="modal-body">
                <h3>Are you sure you want to delete this?</h3>
                <div>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.FirstName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.FirstName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.LastName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.LastName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Biography)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Biography)
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Delete", "Authors", FormMethod.Post, new { data_bind = "submit:deleteAuthor" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color text-center" data-bind="visible:!sending()">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                        <button class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                    <div class="progress" data-bind="visible:sending">
                        <div class="progress-bar progress-bar-info progress-bar-striped active"
                             role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"
                             style="width: 100%">
                            <span class="sr-only"></span>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

BookTest/Views/Authors/Details.cshtml
@model BookTest.Models.Author

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Author</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BookTest/Views/Authors/Edit.cshtml
@model BookTest.Models.Author

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BookTest/Views/Authors/Form.cshtml
@using BookTest.Extensions
@model BookTest.Models.Author

@{
    var isCreate = Model.Id == 0;
    ViewBag.Title = isCreate ? "Create" : "Edit";
}
<div data-bind="visible:!saveCompleted()">
    <h2>@(ViewBag.Title)</h2>
    @using (Html.BeginForm("Create", "Authors", FormMethod.Post, new { data_bind = "submit:validateAndSave" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Author</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       data_bind = "value:author.firstName"
                   }
               })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       data_bind = "value:author.lastName"
                   }
               })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Biography, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Biography, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       data_bind = "value:author.biography"
                   }
               })
                    @Html.ValidationMessageFor(model => model.Biography, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" data-bind="visible:!sending()">
                    <input type="submit" value="@if (isCreate)
                                                {
                                                    @Html.Raw("Create")
                                                }
                                                else
                                                {
                                                    @Html.Raw("Edit");
                                                } " class="btn btn-default" />
                </div>


                <div class="progress" data-bind="visible:sending()">
                    <div class="progress-bar progress-bar-info progress-bar-striped active"
                         role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"
                         style="width: 100%"><span class="sr-only"></span></div>
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/ViewModels/AuthorFormViewModel.js")
    <script>
        var viewModel = new AuthorFormViewModel(@Html.HtmlConvertToJson(Model));
        ko.applyBindings(viewModel);
    </script>
}

BookTest/Views/Authors/Index.cshtml
@using BookTest.Extensions
@using BookTest.Models
@model IEnumerable<BookTest.Models.Author>

@{
    ViewBag.Title = "Index";
    var queryOptions = (QueryOptions)ViewBag.QueryOptions;
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.BuildSortableLink("Id", "Index", "id", queryOptions)
            </th>
            <th>
                @Html.BuildSortableLink("FirstName", "Index", "firstName", queryOptions)
            </th>
            <th>
                @Html.BuildSortableLink("LastName", "Index", "lastName", queryOptions)
            </th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody data-bind="foreach:authors">
        <tr>
            <td data-bind="text:id"></td>
            <td data-bind="text:firstName"></td>
            <td data-bind="text:lastName"></td>
            <td>
                <a data-bind="attr:{href:'@(Url.Action("Details"))/'+id}" class="btn btn-info">Details</a>
                <a data-bind="attr:{href:'@(Url.Action("Edit"))/'+id}" class="btn btn-primary">Edit</a>
                <a data-bind="click:$parent.showDeleteModal,attr:{href:'@(Url.Action("Delete"))/'+id}" class="btn btn-danger">Delete</a>
            </td>
        </tr>
    </tbody>
</table>
@Html.BuildNextPreviousLinks(queryOptions, "index")
@section scripts
{
        @Scripts.Render("~/Scripts/ViewModels/AuthorIndexViewModel.js")
    
    <script>
        var viewModel = new AuthorIndexViewModel(@Html.HtmlConvertToJson(Model));
        ko.applyBindings(viewModel);
    </script>
}